version: '2.4'

services:

  eventstore:
    image: eventstore/eventstore:21.10.1-bionic
    container_name: "cqrs4j-quarkus-example-eventstore"
    environment:
      EVENTSTORE_MEM_DB: "true"
      EVENTSTORE_RUN_PROJECTIONS: "All"
      EVENTSTORE_INSECURE: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
      EVENTSTORE_LOG: "/tmp/log-eventstore"
    ports:
      - "2113:2113"
    networks:
      - cqrs4j-quarkus-example-net

#  jkmq-postgres:
#    image: postgres:11.0
#    container_name: "cqrs4j-quarkus-example-postgres"
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=querydb
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=abc
#    networks:
#      - cqrs4j-quarkus-example-net

  mariadb:
    image: mariadb:10.6
    container_name: "cqrs4j-quarkus-example-mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: xyz
      MYSQL_DATABASE: querydb
      MYSQL_USER: mary
      MYSQL_PASSWORD: abc
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "3306:3306"
    networks:
      - cqrs4j-quarkus-example-net

networks:
  cqrs4j-quarkus-example-net:
    name: cqrs4j-quarkus-example-net
  